const DEFAULT_IMAGE_SCALE = 100;
const MAX_IMAGE_SCALE = 100;
const MIN_IMAGE_SCALE = 25;
const SCALE_STEP = 25;

const MAX_HASHTAGS = 5;
const MAX_HASHTAG_LENGTH = 19;
const MAX_DESCRIPTION_LENGTH = 140;

export { MAX_DESCRIPTION_LENGTH, MAX_HASHTAG_LENGTH, MAX_HASHTAGS,MAX_IMAGE_SCALE, MIN_IMAGE_SCALE, SCALE_STEP, DEFAULT_IMAGE_SCALE };
